<?php

namespace App\Http\Requests\Admin\User;

use Illuminate\Foundation\Http\FormRequest;

class StoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'=> 'required|string',
            'password'=> 'required|string|min:8',
            'email'=>'required|string|unique:users'
        ];
    }


    public function messages()
    {
        return [
            'name.required'=>'Это поле необходимо заполнить',
            'name.string'=>'Это поле должно быть строкой',
            'password.required'=>'Это поле необходимо заполнить',
            'password.string'=>'Это поле должно быть строкой',
            'password.min'=>'Минимальная длина пароля 8 символов',
            'email.required'=>'Это поле необходимо заполнить',
            'email.unique'=>'Пользователь с таким email уже существует',
            'email.string'=>'Это поле должно быть строкой'
            ]; // TODO: Change the autogenerated stub
    }
}
