<?php

namespace App\Http\Requests\Admin\Post;

use Illuminate\Foundation\Http\FormRequest;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'required|string',
            'description'=>'required|string',
            'content' => 'required|string',
            'preview_image' => 'nullable|image',
            'main_image' => 'nullable|image',
            'category_id' => 'required|exists:categories,id',
            'tags_id' => 'nullable|array',
            'tags_id.*' => 'nullable|exists:tags,id',
        ];
    }
    public function messages()
    {
        return [
            'title.required' => 'Это поле необходимо для заполнения',
            'title.string' => 'Данные должны передаваться строкой',
            'description.string' => 'Данные должны передаваться строкой',
            'description.required' => 'Это поле необходимо для заполнения',
            'content.required' => 'Это поле необходимо для заполнения',
            'content.string' => 'Данные должны передаваться строкой',
            'preview_image.required' => 'Это поле необходимо для заполнения',
            'preview_image.image' => 'Данный фаил не является изображением',
            'main_image.required' => 'Это поле необходимо для заполнения',
            'main_image.image' => 'Данный фаил не является изображением'
        ]; // TODO: Change the autogenerated stub
    }
}
